# **Classification of Claims in TikTok Videos**
**First Stage - Analyzing and Inspecting Data**

**Situation:**

We're still in the early *stages* of the project. I've been given access to TikTok's data. To gain clear insights to prepare for a claims classification model, TikTok's provided data must be examined to begin the process of exploratory data analysis (EDA).

# **Inspecting and analyzing data**

In this stage, I will examine data provided and prepare it for analysis.
<br/>

**The purpose** of this project is to investigate and understand the data provided. This activity will:

1.   Acquaint us with the data

2.   Compile summary information about the data

3.   Begin the process of EDA and reveal insights contained in the data

4.   Prepare us for more in-depth EDA, hypothesis testing, and statistical analysis

**The goal** is to construct a dataframe in Python, perform a cursory inspection of the provided dataset, and inform TikTok data team members of our findings.
<br/>
*This activity has three parts:*

**Part 1:** Understanding the situation
* How can we best prepare to understand and organize the provided TikTok information?

**Part 2:** Understanding the data

* Creating a pandas dataframe for data learning and future exploratory data analysis (EDA) and statistical activities.

* Compiling summary information about the data to inform next steps.

**Part 3:** Understanding the variables

* Using insights from our examination of the summary data to guide deeper investigation into variables.

# **Identifying data types and compiling summary information**

Throughout project notebooks, we'll be using the problem-solving framework PACE. Each notebook components are labeled with the respective PACE stage: Plan, Analyze, Construct, and Execute.

# **PACE stages**

## **PACE: Plan**

### **Part 1. Understanding the situation**

This can be done by considering the overall project goals, reviewing the data dictionary, making some observational operations and descriptive **statistics**. Also by creating a pandas dataframe for data learning and future exploratory data analysis and statistical activities, and compiling summary information about the data to inform future steps, we can best prepare to understand and organize the provided information.

## **PACE: Analyze**

### **Part 2a. Imports and data loading**

I'll Start by importing the packages that we'll **need** to load and explore the dataset.

In [1]:
# Importing packages
import pandas as pd
import numpy as np

Then, I'll load the dataset into a dataframe. This will help us conduct data manipulation, exploratory data analysis, and statistical activities.

In [3]:
# Loading dataset into dataframe
data = pd.read_csv("tiktok_dataset.csv", index_col=0)

### **Part 2b. Understanding the data - Inspecting the data**



- When reviewing the first few rows of the dataframe, we can see the data is well formated, where each row represent an observation of a video.

- When reviewing the `data.info()` output, we notice that only 5 of 12 column don't have missing values. All other columns have null values. 8 columns are numeric, others are of type `object`.

- When reviewing the `data.describe()` output, we notice that numeric variables are highly deviated from the mean value. And the 25th/75th percintiles are also highly deviated. Columns that contain outliers are video_like_count , video share count , video_download_count and video_comment_count .

In [4]:
# Displaying and examining the first ten rows of the dataframe
data.head(10)

,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
#,,,,,,,,,,,
1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0
2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0
3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0
4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0
5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0
6,claim,8972200955,35,someone shared with me that gross domestic pro...,not verified,under review,336647.0,175546.0,62303.0,4293.0,1857.0
7,claim,4958886992,16,someone shared with me that elvis presley has ...,not verified,active,750345.0,486192.0,193911.0,8616.0,5446.0
8,claim,2270982263,41,someone shared with me that the best selling s...,not verified,active,547532.0,1072.0,50.0,22.0,11.0
9,claim,5235769692,50,someone shared with me that about half of the ...,not verified,active,24819.0,10160.0,1050.0,53.0,27.0
10,claim,4660861094,45,someone shared with me that it would take a 50...,verified,active,931587.0,171051.0,67739.0,4104.0,2540.0

In [5]:
# Getting summary info
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19382 entries, 1 to 19382
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   claim_status              19084 non-null  object
 1   video_id                  19382 non-null  int64
 2   video_duration_sec        19382 non-null  int64
 3   video_transcription_text  19084 non-null  object
 4   verified_status           19382 non-null  object
 5   author_ban_status         19382 non-null  object
 6   video_view_count          19084 non-null  float64
 7   video_like_count          19084 non-null  float64
 8   video_share_count         19084 non-null  float64
 9   video_download_count      19084 non-null  float64
 10  video_comment_count       19084 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.8+ MB

In [ ]:
# Getting summary statistics
data.describe()

,#,video_id,video_duration_sec,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count,likes_per_view,comments_per_view,shares_per_view
count,19382.000000,1.938200e+04,19382.000000,19084.000000,19084.000000,19084.000000,19084.000000,19084.000000,19084.000000,19084.000000,19084.000000
mean,9691.500000,5.627454e+09,32.421732,254708.558688,84304.636030,16735.248323,1049.429627,349.312146,0.276093,0.000954,0.054860
std,5595.245794,2.536440e+09,16.229967,322893.280814,133420.546814,32036.174350,2004.299894,799.638865,0.173006,0.001326,0.050597
min,1.000000,1.234959e+09,5.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4846.250000,3.430417e+09,18.000000,4942.500000,810.750000,115.000000,7.000000,1.000000,0.130240,0.000098,0.014445
50%,9691.500000,5.618664e+09,32.000000,9954.500000,3403.500000,717.000000,46.000000,9.000000,0.264037,0.000455,0.039739
75%,14536.750000,7.843960e+09,47.000000,504327.000000,125020.000000,18222.000000,1156.250000,292.000000,0.398482,0.001268,0.081864
max,19382.000000,9.999873e+09,60.000000,999817.000000,657830.000000,256130.000000,14994.000000,9599.000000,0.666648,0.010280,0.265956

### **Part 2c. Understanding the data - Investigating the variables**

In this stage, we'll will begin to investigate the variables more closely to better understand them.

We know from the project proposal that the ultimate objective is to use machine learning to classify videos as either claims or opinions. A good first step towards understanding the data might therefore be examining the `claim_status` variable. we'll begin by determining how many videos there are for each different claim status.

In [6]:
# The different values for claim status and how many of each are in the data
data['claim_status'].value_counts(normalize=True)

claim_status
claim      0.503458
opinion    0.496542
Name: proportion, dtype: float64

> We notice that the percentages are approximately equal.

Next, we'll examine the engagement trends associated with each different claim status.

This can be dine by using boolean masking to filter the data according to claim status, then calculating the mean and median view counts for each claim status.

In [7]:
# The average view count of videos with "claim" status
print(data[data['claim_status'] == 'claim']['video_view_count'].mean())
data[data['claim_status'] == 'claim']['video_share_count'].median()

501029.4527477102

17997.5

In [8]:
# The average view count of videos with "opinion" status
print(data[data['claim_status'] == 'opinion']['video_view_count'].mean())
data[data['claim_status'] == 'opinion']['video_view_count'].median()

4956.43224989447

4953.0

We notice that the median and mean for each indivisual value are approximately the same. However, there is a huge differance in the average views when the status is different, which indicates an obvious relation. <br>

Now, we'll examine trends associated with the ban status of the author using `groupby()` to calculate how many videos there are for each combination of categories of claim status and author ban status.

In [9]:
# Counts for each group combination of claim status and author ban status
data.groupby(['claim_status', 'author_ban_status'], as_index=False).size()

  claim_status author_ban_status  size
0        claim            active  6566
1        claim            banned  1439
2        claim      under review  1603
3      opinion            active  8817
4      opinion            banned   196
5      opinion      under review   463

We notice that there is a direct relation between video being `claim` and author being `banned`, since banned videos at the `claim` status are much higher than in `opinion`. The reason of this might be due to the fact that banned authors content depends highly on claims for aquiring more traffic.

We,ll ontinue investigating engagement levels focusing on `author_ban_status`.

Let's calculate the median video shares count of each author ban status.

In [10]:
data.groupby('author_ban_status')['video_share_count'].median()

author_ban_status
active            437.0
banned          14468.0
under review     9444.0
Name: video_share_count, dtype: float64

It's obious that banned users have much more shares on their vidoes, which indicated an important correlation. Also, `claim` videos appears to have much more shares.

Using `groupby()` to group the data by `author_ban_status`, then using `agg()`, we can get the count, mean, and median of each of the following columns:
* `video_view_count`
* `video_like_count`
* `video_share_count`

In [11]:
data.groupby('author_ban_status')[['video_view_count','video_like_count','video_share_count']].agg(['count','mean','median'])

                  video_view_count                          video_like_count  \
                             count           mean    median            count
author_ban_status
active                       15383  215927.039524    8616.0            15383
banned                        1635  445845.439144  448201.0             1635
under review                  2066  392204.836399  365245.5             2066

                                           video_share_count                \
                            mean    median             count          mean
author_ban_status
active              71036.533836    2222.0             15383  14111.466164
banned             153017.236697  105573.0              1635  29998.942508
under review       128718.050339   71204.5              2066  25774.696999


                    median
author_ban_status
active               437.0
banned             14468.0
under review        9444.0

We can see that banned authore have much more views, likes and shares on ther videos compared to active uers.

Now, let's create three new columns to better understand engagement rates:
* `likes_per_view`: the number of likes divided by the number of views for each video
* `comments_per_view`: the number of comments divided by the number of views for each video
* `shares_per_view`: the number of shares divided by the number of views for each video

In [12]:
# Creating a likes_per_view column
data['likes_per_view'] = data['video_like_count']/data['video_view_count']

# Creating a comments_per_view column
data['comments_per_view'] = data['video_comment_count']/data['video_view_count']
# Creating a shares_per_view column
data['shares_per_view'] = data['video_share_count']/data['video_view_count']

Using`groupby()` to compile the information in each of the three newly created columns for each combination of categories of claim status and author ban status, then using `agg()` to calculate the count, the mean, and the median of each group. we get:

In [13]:
data.groupby(['claim_status','author_ban_status'])[['likes_per_view','comments_per_view','shares_per_view']].agg(['count','mean','median'])

                               likes_per_view                      \
                                        count      mean    median
claim_status author_ban_status
claim        active                      6566  0.329542  0.326538
             banned                      1439  0.345071  0.358909
             under review                1603  0.327997  0.320867
opinion      active                      8817  0.219744  0.218330
             banned                       196  0.206868  0.198483
             under review                 463  0.226394  0.228051

                               comments_per_view                      \
                                           count      mean    median
claim_status author_ban_status
claim        active                         6566  0.001393  0.000776
             banned                         1439  0.001377  0.000746
             under review                   1603  0.001367  0.000789
opinion      active                         8817  0.000517  0.000252
             banned                          196  0.000434  0.000193
             under review                    463  0.000536  0.000293

                               shares_per_view
                                         count      mean    median
claim_status author_ban_status
claim        active                       6566  0.065456  0.049279
             banned                       1439  0.067893  0.051606
             under review                 1603  0.065733  0.049967
opinion      active                       8817  0.043729  0.032405
             banned                        196  0.040531  0.030728
             under review                  463  0.044472  0.035027

`opinion` videos seem to have more active authors with less views, shares, comments and likes per view compared to `claim` videos but those percentages here are higher for active authors. <br>
On the other hand, `claim` videos seem to have more banned authors with higher views, shares, comments and likes per view compared to `opinion` videos and those percentages here are higher for banned authors.

## **PACE: Construct**
No need for any constructing in the current stage of the project.

## **PACE: Execute**

### **What we can summarize for the TikTok data team:**

+ 50.4% of the data are `claim` and 49.6% are `opinion` .
+ Most important factors related to the `claim` status is author `banned` states and higher values of views, likes, shares and comments.
+ `claim` videos seem to have more banned authors with higher views, shares, comments and likes per view compared to `opinion` videos, and those percentages here are higher for `banned` authors.